#Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
    register-with-eureka: false  
    fetch-registry: false        
  instance:
    prefer-ip: true 
# loggers
logging:
  level:
    root: INFO                     # Default logging level
    org.springframework.cloud: INFO   # Spring Cloud logging (including Eureka)
    org.springframework.web: DEBUG    # Spring MVC logging
    com.netflix.eureka: DEBUG        # Eureka client-specific logging

# Key for ensuring property coming from Git config file only
GitConfig : true
