spring:
  application:
    name: Individual Expense

#Server Configuration
server:
  port: 8083

# noinspection undefined
# Expense service URLs
expense:
  service:
    url:
      base: "http://localhost:8082/expense/"
      getByDate: "getByDate/"

# noinspection undefined
# Tenant Service URLs

tenant:
  service:
    url :
      base: "http://localhost:8081/tenant/"
      count: "count"
