spring:
  application:
    name: individual-expense-service
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/




#Server Configuration
server:
  port: 8083

# noinspection undefined
# Expense service URLs
expense:
  service:
    url:
      base: "http://localhost:8082/expense/"
      #base: "http://expense-service/expense/"
      getByDate: "getByDate/"

# noinspection undefined
# Tenant Service URLs

tenant:
  service:
    url :
      base: "http://localhost:8081/tenant/"
      count: "count"

#Eureka Configurations
